export const FOUR_CHARACTERS_REGEX = /.{4}/; // MIX 4 letters
export const EMAIL = /[a-z0-9._%+-]+@[a-z0-9.-]+.[a-z]{2,3}$/; // Valid email
​export const FIRST_NUMBER = /^[3]\d*$/; // first number phone 3
export const HAS_NUMBER = /[0-9]/; // Has number
export const KEY_ENCRYPT_DESENCRYPT = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJBcGlLZXkiOiIwMzAxMDYiLCJWZXJzaW9uIjoiMS4wLjAifQ.OJ7pEEf3b0tPHwdWIn7-v18tYnMeYhTU9UT8zDSEtrg"
export const TEXT_ONE ="Para comenzar, por favor ingresa <strong> tu número celular.</strong>"
export const TEXT_TWO="Digíta el código que recibiste vía <strong> mensaje de texto</strong> al "
export const OINK="assets/img/Oink.svg"
export const BACK="assets/img/Backspace.svg"
export const CHECK="assets/img/Check-key.svg"